import { readFileSync } from 'node:fs';
import { type CryptoKey, SignJWT, importPKCS8, importSPKI, jwtVerify } from 'jose';

const JWT_ALG = 'RS256';
const JWT_TTL_SECONDS = 90 * 24 * 60 * 60;

let privateKeyPromise: Promise<CryptoKey> | null = null;
let publicKeyPromise: Promise<CryptoKey> | null = null;

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(`${name} env var is required`);
  }
  return value;
}

/**
 * Railway's filesystem is ephemeral, so the PEM can't just live at a fixed
 * path there — JWT_PRIVATE_KEY/JWT_PUBLIC_KEY (base64-encoded PEM content,
 * to survive env-var newline handling) take priority when set. Local dev
 * keeps using JWT_PRIVATE_KEY_PATH/JWT_PUBLIC_KEY_PATH (plain PEM files under
 * keys/, generated by generate-jwt-keys.ts) since those env vars are never
 * set outside a deploy environment.
 */
function readPem(envVarName: string, pathEnvVarName: string): string {
  const encoded = process.env[envVarName];
  if (encoded) {
    return Buffer.from(encoded, 'base64').toString('utf-8');
  }
  return readFileSync(requireEnv(pathEnvVarName), 'utf-8');
}

function getPrivateKey(): Promise<CryptoKey> {
  if (!privateKeyPromise) {
    const pem = readPem('JWT_PRIVATE_KEY', 'JWT_PRIVATE_KEY_PATH');
    privateKeyPromise = importPKCS8(pem, JWT_ALG);
  }
  return privateKeyPromise;
}

function getPublicKey(): Promise<CryptoKey> {
  if (!publicKeyPromise) {
    const pem = readPem('JWT_PUBLIC_KEY', 'JWT_PUBLIC_KEY_PATH');
    publicKeyPromise = importSPKI(pem, JWT_ALG);
  }
  return publicKeyPromise;
}

export interface SessionTokenPayload {
  sub: string;
  jti: string;
}

export async function signSessionToken(contactId: string, jti: string): Promise<string> {
  const key = await getPrivateKey();
  return new SignJWT({ sub: contactId, jti })
    .setProtectedHeader({ alg: JWT_ALG })
    .setIssuedAt()
    .setExpirationTime(`${JWT_TTL_SECONDS}s`)
    .sign(key);
}

export async function verifySessionToken(token: string): Promise<SessionTokenPayload> {
  const key = await getPublicKey();
  const { payload } = await jwtVerify(token, key, { algorithms: [JWT_ALG] });

  if (typeof payload.sub !== 'string' || typeof payload.jti !== 'string') {
    throw new Error('malformed session token payload');
  }

  return { sub: payload.sub, jti: payload.jti };
}
